### ISSUE TITLE
"Invalid  parameter: TopicArn" on create subscription for SNS "NewSentinel2Product"

### ISSUE THREAD

**Issue by dkingram** [sinergise/Sentinel2ProductIngestor#2]
Hi:
I am attempting to create an AWS Lambda SNS subscription to the topic shown in your README.md as:
    ARN: arn:aws:sns:eu-west-1:214830741341:NewSentinel2Product
but it is returning an error:

Can you help?
![image](https://user-images.githubusercontent.com/1108474/30835774-3e0f1c8a-a217-11e7-9686-67c573dd3815.png)

**Comment by pkolaric** [comment]
Hello,
It's probably due to some permission issues, you have to allow invocation of your lambda function from SNS topic. Check 
http://docs.aws.amazon.com/lambda/latest/dg/with-sns-create-x-account-permissions.html

**Comment by dkingram** [comment]
AWS support was able to duplicate this issue.  However, when subscribing from AWS region 'eu-west-1' they were able to create a subscription.  I also was able to subscribe a Lambda function to the topic:
`aws sns subscribe --region 'eu-west-1' --topic-arn 'arn:aws:sns:eu-west-1:214830741341:NewSentinel2Product' --protocol lambda --notification-endpoint arn:aws:lambda:us-west-2:<AWS Account Number>:function:test`

**Comment by brycejohnston** [comment]
not to revive closed issue, but I too had to make sure SQS was using eu-west-1 region in order to subscribe to the SNS topic, along with setting the required permission for SendMessage (also had to use standard queue, FIFO didn't seem to get messages). Other regions would give an error.

**Comment by riyapyan** [comment]
@dkingram **try this** 😉 [UPDATE PROPER **Region name**]

![image](https://user-images.githubusercontent.com/80042414/207002534-f06d76b6-b966-4b39-8cc8-f3db59df5aea.png)
